### ISSUE TITLE
twitter.config problem

### ISSUE THREAD

**Issue by ravisharma-viz** [jsturtevant/twitter-stream#1]
Hi,

I am trying to use this example and created a twitter.config files as shown by you in the readme.md file. But I am getting this ""The format of a configSource file must be an element containing the name of the section. (D:\PROJECTS\twitter-stream-master\twitter.example\bin\Debug\twitter.config line 2)"" error.

Please help.

Thanks and best regards,
- Ravi

**Comment by jsturtevant** [comment]
Hi,
Documentation was wrong.  I've updated the read.me.  Your `twitter.config` file should look like this:

``` c#
<twitter.example.Properties.Settings>
  <setting name="secret" serializeAs="String">
    <value>your secret</value>
  </setting>
  <setting name="key" serializeAs="String">
    <value>your key</value>
  </setting>
  <setting name="accessToken" serializeAs="String">
    <value>your access token</value>
  </setting>
  <setting name="accessTokenSecret" serializeAs="String">
    <value>your access token secret</value>
  </setting>
</twitter.example.Properties.Settings>
```

**Comment by ravisharma-viz** [comment]
Thanks for the update..

Regards
